# https://octokit.github.io/rest.js
# https://github.com/actions/toolkit/blob/master/packages/github/src/context.ts

name: PR Linter
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - edited
      - opened
      - synchronize
      - reopened

jobs:
  build:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Validate
        run: yarn lint