name: PR Title linter

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        with:
            types: |
              feat
              fix
              docs
              style
              ui
              refactor
              perf
              test
              build
              ci
              chore
              revert
              release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

